#pragma config(Sensor, S1,     touchSensor,              sensorTouch)
#pragma config(Sensor, S2,     compassSensor,            sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,              sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,              sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/***********************************  *\
|*  Programmer: Dominic Diaz          *|
|*                                    *|
|*code completes Line Runner Challenge*|
|*  MAKE SURE TO "SAVE AS" INSTEAD    *|
\***********************************  */

/* MIT License

Copyright (c) 2022 lolpro11 and Dominic Diaz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

task main()
{
	
	//displayString(1, "Dominic Diaz");
    displayString(1, "Andrew Cini");
	displayString(3, "Joshua Wong");
    displayString(5, "Abraham Orea");

	while (SensorValue(touchSensor) == 0) {
		if (SensorValue(lightSensor) > 20) {
            displayTextLine(2, "Moving Forward...");
            motor[motorC] = 30;
            motor[motorB] = 30;
		}
		else if (SensorValue(lightSensor) < 15){
            displayTextLine(2, "Moving Backward...");
            motor[motorC] = -100;
            motor[motorB] = -100;
            wait1Msec(1000);
		}
	}
}
